name: develop-branch-plan

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
    paths:
      - "environments/**"
      - "modules/**"
      - "terraform/**"

jobs:
  # NOTE: validate/format
  pre-check:
    uses: minikocha/branch-deploy-test/.github/workflows/pre-check.yaml@develop

  develop-plan:
    needs: pre-check
    uses: minikocha/branch-deploy-test/.github/workflows/terragrunt-plan.yaml@develop
    with:
      DEPLOYMENT_TARGET: environments/develop

  common-plan:
    needs: pre-check
    uses: minikocha/branch-deploy-test/.github/workflows/terragrunt-plan.yaml@develop
    with:
      DEPLOYMENT_TARGET: environments/common
